-- TODO: Make test
-- local plugin = require("irc_nvim")
--
-- describe("setup", function()
--   it("works with default", function()
--     assert(plugin.test({ args = "Hello!" }) == "Hello!", "my first function with param = Hello!")
--   end)
--
--   it("works with custom var", function()
--     plugin.setup({ opt = {
--       server = "irc.libera.chat",
--     } })
--     assert(plugin.test({ args = "custom" }) == "custom", "my first function with param = custom")
--   end)
-- end)
